# Generated by Django 3.0.6 on 2020-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0003_auto_20200524_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='mycart/images'),
        ),
    ]
